[project]
name = "DoctorQ"
version = "0.1.0"
description = "Queue management system for doctors"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "nicegui>=2.10.1",
    "pydantic>=2.10.6",
    "pytest>=8.3.4",
]
